### ISSUE TITLE
Unable to use sm.pl.image_viewer

### ISSUE THREAD

**Issue by josenimo** [labsyspharm/scimap#16]
Dear SciMap developer,

I am trying to visualize my data produced in MCMICRO spatially in the original image. 
I get two different error messages: 
IndexError: Index is out of bounds for axis 0 with size 8
AssertionError: number of channel names (9) must match number of channels (8)

I am uploading the h5ad file, and the image.
[unmicst-Test_Image_06_4+5_cell.h5ad.csv](https://github.com/labsyspharm/scimap/files/7950553/unmicst-Test_Image_06_4%2B5_cell.h5ad.csv)
Image and Jupyter Notebook Download: https://filetransfer.mdc-berlin.de/?u=9ay4eeE6&p=AmDmMeW3

Thank you!
Best,
Jose

**Comment by ajitjohnson** [comment]
Hi @josenimo Can you please check you `.csv` file?
The `mcmicro_to_scimap` function expects the native output of the `mcmicro` pipeline (or at least similar with all required column names). It looks like the first column of your `.csv` file does not have `CellID` which the function expects. 

This has led to the creation of a pseudo column called `'Unnamed: 0'` and subsequently does not match the number of channels in your image. 

As a quick workaround just run the following like before running `sm.pl.image_viewer` function.

```
adata.uns['all_markers'].remove('Unnamed: 0')
# Run viewer
sm.pl.image_viewer (image_path, adata)
```

**Comment by josenimo** [comment]
Dear @ajitjohnson,
Thank you, for your response. After few rounds of testing, I finally realized I was using the incorrect csv file. I was using the one found in cell-states/scimap which has the empty cell. Using the csv found in quantification worked perfectly.

Thank you for your support!
Best
Jose

**Comment by ajitjohnson** [comment]
@ArtemSokolov Not sure if the above was the intended output in `cell-states`?

**Comment by ArtemSokolov** [comment]
Hi @ajitjohnson,

Here is the regular expression MCMICRO uses to decide which outputs from `cell-states` modules should be copied from the work directory to the project directory:

https://github.com/labsyspharm/mcmicro/blob/46abd97bc04ff9e848a082bb7f86d20389caf4b1/modules/cell-states.nf#L18

This is in addition to `plots/` and `qc/` subdirectories, if a module produces them:

https://github.com/labsyspharm/mcmicro/blob/46abd97bc04ff9e848a082bb7f86d20389caf4b1/modules/lib/worker.nf#L57-L60

What should I change the regular expression to, so that it doesn't capture that file?

An alternative solution is to have `scimap` output that file to a subdirectory (something other than `plots/` and `/qc`), so that it doesn't get captured by `*.{csv,h5ad}`.

**Comment by ArtemSokolov** [comment]
Looks like this may also be related to #9
